# fly.toml app configuration file generated for blogapp-rails on 2025-01-05T19:07:08-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blogapp-rails'
primary_region = 'gru'
console_command = '/rails/bin/rails console'

[build]

[env]
  RAILS_ENV = 'production'

[processes]
  app = "sh -c 'bundle exec puma -C config/puma.rb & bundle exec sidekiq'"

[mounts]
  source = 'storage_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
